Remove forced u" on string value that causes
TypeError: can only join an iterable of bytes (item 3 has type 'unicode'):
...
  File "/home/jkenny/env/lib/python2.7/site-packages/scons-3.0.1/SCons/Action.py", line 185:
    return _function_contents(obj.__call__.__func__)
  File "/home/jkenny/env/lib/python2.7/site-packages/scons-3.0.1/SCons/Action.py", line 301:
    contents = [_code_contents(func.__code__, func.__doc__)]
  File "/home/jkenny/env/lib/python2.7/site-packages/scons-3.0.1/SCons/Action.py", line 264:
    contents.extend(bytearray(',', 'utf-8').join(z))