Fix -fsanitize flag handling
These parameters need to be passed to both the compiler and the linker,
otherwise lots of "undefined reference to `__asan_stack_malloc_0'"
errors get emitted at link time, since the appropriate library is not
linked in.